# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 19:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_restuarant_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(default='', max_length=511),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keyword',
            name='is_main',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='bidding_end_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 27, 19, 37, 14, 494643)),
        ),
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.CharField(max_length=511, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='was_successful',
            field=models.NullBooleanField(),
        ),
    ]
