# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160228_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_url',
            field=models.CharField(max_length=1023, null=True),
        ),
    ]
