# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_item_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='restuarant',
            name='address',
            field=models.CharField(default=b'3180 18th St.', max_length=255),
        ),
    ]
