# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 20:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160227_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bidding_end_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 27, 21, 0, 26, 168406)),
        ),
    ]
