# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_restuarant_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
